version: '2.4'

services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './data:/usr/src/app/data:delegated'
      - './output:/usr/src/app/output:delegated'
      - './src:/usr/src/app/src:delegated'
      - './test:/usr/src/app/test:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000